#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 15 14:16:47 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 63fc52f5f24842c79987f0c2980bbd21 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_SimpleLogicModule_behav xil_defaultlib.tb_SimpleLogicModule xil_defaultlib.glbl -log elaborate.log"
xelab -wto 63fc52f5f24842c79987f0c2980bbd21 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_SimpleLogicModule_behav xil_defaultlib.tb_SimpleLogicModule xil_defaultlib.glbl -log elaborate.log

