#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 15 20:13:21 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto a1962553fbe644a49ddaa88b7a39dde0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot SimpleLogicModuleAXIIP_v1_0_behav xil_defaultlib.SimpleLogicModuleAXIIP_v1_0 xil_defaultlib.glbl -log elaborate.log"
xelab -wto a1962553fbe644a49ddaa88b7a39dde0 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot SimpleLogicModuleAXIIP_v1_0_behav xil_defaultlib.SimpleLogicModuleAXIIP_v1_0 xil_defaultlib.glbl -log elaborate.log

